#!/usr/bin/env bash
#Install nginx on your web-01 server
#Nginx should be listening on port 80
#When querying Nginx at its root / with a GET request (requesting a page)
# using curl, it must return a page that contains the string Hello World!
# Update package index and install nginx
apt-get update
apt-get install -y nginx

# Configure nginx to serve "Hello World!" on root
echo "Hello World!" >> /var/www/html/index.html

# Restart nginx
service nginx restart
