#!/usr/bin/env bash

# Install nginx
sudo apt-get update
sudo apt-get -y install nginx

# Configure redirection
sudo sed -i '/server_name _;/a \\tlocation /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default

# Configure custom 404 page
sudo sh -c 'echo "Ceci n'\''est pas une page" > /usr/share/nginx/html/404.html'

# Update Nginx configuration to use custom 404 page
sudo sed -i '/server_name _;/a \\tlocation / {\n\t\ttry_files $uri $uri/ =404;\n\t}' /etc/nginx/sites-available/default
sudo sed -i '/server_name _;/a \\terror_page 404 /404.html;' /etc/nginx/sites-available/default

# Restart nginx to apply changes
sudo service nginx restart
