#!/usr/bin/env bash
# This script displays numbers from 1 to 100. Displays FizzBuzz when the number is a multiple of 3 and 5. Displays Fizz when the number is multiple of 3. Displays Buzz when the number is a multiple of 5, Otherwise, displays the number. All In a list format

for num in {1..100}; do
  divisible_by_3=$(( $num % 3 == 0 ))
  divisible_by_5=$(( $num % 5 == 0 ))

  if [[ $divisible_by_5 && $divisible_by_3 ]]; then
    echo "FizzBuzz"
  elif [[ $divisible_by_3 ]]; then
    echo "Fizz"
  elif [[ $divisible_by_5 ]]; then
    echo "Buzz"
  else
    echo $num
  fi
done
